name: 'Continuous Delivery'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDS }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure docker for GCP
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: gcr.io/absolute-water-489804-f6/github.com/panchojr7/latam-challenge:latest
          build-args: |
            HTTP_PORT=80

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          image: gcr.io/absolute-water-489804-f6/github.com/panchojr7/latam-challenge:latest
          service: latam-challenge
          region: us-central1
          flags: "--min-instances=1 --cpu=1 --memory=512Mi --port=80 --allow-unauthenticated"